version: '2'
services:
  vault:
    image: vault:1.2.1
    ports:
      - "8200:8200"
    restart: always
    volumes:
      - ${PWD}/config.json:/vault/config/config.json
      - vault_data:/vault/file
      - vault_backup:/backup
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/config.json

volumes:
  vault_data:
  vault_backup:
